### ISSUE TITLE
HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by MlgmXyysd** [ConnectedGames/MCMirror#144]
https://mcmirror.io/downloads/Spigot

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Only main page can access.

**Comment by fionera** [comment]
Thanks for the Info :) I just fixed it ^^
