### ISSUE TITLE
mcmirror.io not sending the correct media type

### ISSUE THREAD

**Issue by TiagoCN** [ConnectedGames/MCMirror#146]
**Describe the bug**
mcmirror.io not sending the correct media type.
When using Firefox, this causes files to be shown as plain text instead of being downloaded.
Although, this seems to not happen in Chrome.

This appears to be happening because the server is sending `content-type: text/plain` instead of the proper media type or `content-type: application/octet-stream`.

**To Reproduce**
1. Open Firefox
2. Go to https://mcmirror.io/ or https://archive.mcmirror.io/
3. Click on a random file
4. See the behavior

**Expected behavior**
Firefox should automagically start downloading the files but instead shows a bunch of random characters.

**Additional context**
I am using Firefox Version 67.0.4

**Comment by fionera** [comment]
Thanks for the issue :D It was an error in the nginx config. Its fixed now
