### ISSUE TITLE
Change CatServer link from the software list

### ISSUE THREAD

**Issue by Luohuayu** [ConnectedGames/MCMirror#150]
https://github.com/Luohuayu/CatServer
This is the link of the author, the previous link from the software list is also this

**Comment by Luohuayu** [comment]
This is old repo of all commits, this can prove that I am the author
https://github.com/Luohuayu/CatServerPro
I refactored the project because it violated eula

**Comment by KomiMoe** [comment]
I am also one of the developers, please change the link to this.thx
