### ISSUE TITLE
建议添加forge和fabric镜像

### ISSUE THREAD

**Issue by forestbat** [ConnectedGames/MCMirror#152]
存在纯forge端和纯fabric端，对mod的编写者也有帮助。

**Comment by fionera** [comment]
Could you please write english?

**Comment by forestbat** [comment]
What？Are you not Chinese？I advice you to add forge and fabric to this website because there are also some people use pure forge and fabric to create their server。

**Comment by kasuganosoras** [comment]
这个仓库的创建人不是中国人，你可以 Fork 然后修改，提交 Pull Request
