### ISSUE TITLE
Some server core is empty.

### ISSUE THREAD

**Issue by MlgmXyysd** [ConnectedGames/MCMirror#76]
You can download it from my mirror.
https://github.com/MlgmXyysd/Mirror

**Comment by sgdc3** [comment]
https://archive.mcmirror.io/ ;)

**Comment by MlgmXyysd** [comment]
> https://archive.mcmirror.io/ ;)

Provide you with some little-known servers. :)

**Comment by fionera** [comment]
@MlgmXyysd Do you have a directory listing or api so I could download everything? :D

**Comment by MlgmXyysd** [comment]
@fionera Yes, view help.php.I use different storage between page and storage.

**Comment by MlgmXyysd** [comment]
:)

**Comment by MlgmXyysd** [comment]
(Download api use two redirect, curl may make some magic problem...You can use browser to download.)

**Comment by MlgmXyysd** [comment]
(Some core's website is shutdown.Use WayBackMachine to view them.)

**Comment by kasuganosoras** [comment]
惊了，你居然在这里
~~又在宣传你的镜像站~~
